// Cubism 2 Live2D renderer (see docs/LIVE2D-SCHEMA.md).

export {
  animQueue,
  animValues,
  applyProps,
  createAnim,
  loadParam,
  playReaction,
  renderFrame,
  saveParam,
  tickAnim,
  EyeBlink,
  ParamStore,
  type AnimOptions,
  type AnimState,
} from "./anim";
export { Live2DModel, type Live2DModelHandle, type Live2DModelProps } from "./Live2DModel";
export {
  boundsOf,
  composeInto,
  evalDeformers,
  evalMeshFrame,
  evalParamValues,
  evalPose,
  ffdInto,
  ffdPoint,
  formWeights,
  lerpForms,
  makeRotXform,
  rotFormFromRow,
  rotInto,
  rotPoint,
  type DeformerEval,
  type MeshFrame,
  type ModelPose,
  type ParamValues,
  type RotForm,
  type RotXform,
} from "./deform";
export { Live2DRenderer } from "./gl";
export {
  clearLive2DCache,
  live2dModelUrl,
  loadLive2D,
  loadLive2DAnim,
  loadLive2DCatalog,
  type AnimBundle,
  type CatalogEntry,
  type LoadedLive2D,
} from "./load";
export {
  createMotionEnt,
  fadeWeight,
  parseMotion,
  Live2DMotion,
  MotionQueueManager,
  MTN_LAYOUT_ANCHOR_X,
  MTN_LAYOUT_ANCHOR_Y,
  MTN_LAYOUT_SCALE_X,
  MTN_LAYOUT_SCALE_Y,
  MTN_LAYOUT_X,
  MTN_LAYOUT_Y,
  MTN_PARAM,
  MTN_PARTS_VISIBLE,
  type MotionCurve,
  type MotionEnt,
  type ParamTarget,
  type ParsedMotion,
} from "./motion";
export {
  parsePhysics,
  PhysicsHair,
  L2DPhysics,
  type PhysicsHairSpec,
  type PhysicsJson,
  type PhysicsSrcSpec,
  type PhysicsTargetSpec,
} from "./physics";
export type {
  BlendMode,
  ClipJson,
  DeformerJson,
  GridAt,
  GridBind,
  KeyformGrid,
  MeshJson,
  ModelJson,
  ModelParam,
  RotDeformerJson,
  WarpDeformerJson,
} from "./types";