import { t as tr } from "../i18n/t";
// Asset manifest (tools/asset-pipe) and URL helpers.

/** Stand/kv/sd/sdHappy/namePlate are the extracted sources; the `*Thumb` kinds are
 * display-size WebPs generated by tools/asset-pipe/thumbs.py (same art, less weight). */
export type CharArtKind = "stand" | "thumb" | "kv" | "sd" | "sdThumb" | "sdHappy" | "sdHappyThumb" | "namePlate";

interface Manifest {
  resources: Record<string, string>;
  characters: Record<string, Partial<Record<CharArtKind, string>>>;
  bands: Record<string, string>;
  rooms: Record<string, string>;
  cards: Record<string, string>;
  fx: Record<string, string>;
  scene: { img: Record<string, string>; audio: Record<string, string> };
  fonts: Record<string, string>;
}

let manifest: Manifest | null = null;
const BASE = "/assets/";

export async function loadManifest(): Promise<void> {
  const r = await fetch(BASE + "manifest.json");
  if (!r.ok) throw new Error(tr("boot.manifestError"));
  manifest = (await r.json()) as Manifest;
}

const EMPTY: Manifest = { resources: {}, characters: {}, bands: {}, rooms: {}, cards: {}, fx: {}, scene: { img: {}, audio: {} }, fonts: {} };

/** Until the manifest is loaded (the boot screen), every lookup is simply "no asset". */
function m(): Manifest {
  return manifest ?? EMPTY;
}

const url = (p?: string) => (p ? BASE + p : "");

/** `Resources.Load(path)` -- case-insensitive, like Unity. */
export function res(path: string): string {
  return url(m().resources[path.toLowerCase()]);
}

export function charArt(artId: string, kind: CharArtKind = "sd"): string {
  const a = m().characters[artId];
  // A missing thumb falls back to the art it was made from (never the other way).
  const alt =
    kind === "thumb" ? a?.stand ?? a?.sd :
    kind === "sdThumb" ? a?.sd ?? a?.stand :
    kind === "sdHappyThumb" ? a?.sdHappy ?? a?.sd ?? a?.stand :
    a?.sd ?? a?.stand;
  return url(a?.[kind] ?? alt);
}

export function cardArt(id: string): string {
  if (!id) return "";
  const man = m();
  const a = man.cards[id];
  if (a) return url(a);
  // Skill stand-ins (`skill:<band>:<skill>` -- the 团卡 / character skill) have
  // no card art; their band logo stands in so a prompt that names one still
  // shows a picture. Bands the asset set has no logo for fall back to the card
  // back, never to a broken image.
  if (id.startsWith("skill:")) {
    const owner = id.slice("skill:".length).split(":")[0];
    return url(man.bands[owner]) || url(man.scene?.img?.card_back);
  }
  return url(man.scene?.img?.card_back) || url(undefined);
}

export function bandLogo(band: string): string {
  return url(m().bands[band]);
}

export function sceneImg(name: string): string {
  return url(m().scene.img[name]);
}

export function fx(name: string): string {
  return url(m().fx[name]);
}

/** Register the CJK web fonts extracted from the game (Source Han Rounded CN, OFL). */
export function installFonts(): void {
  const f = m().fonts;
  const css: string[] = [];
  const face = (family: string, weight: number, file?: string) =>
    file && css.push(`@font-face{font-family:"${family}";src:url("${url(file)}") format("truetype");font-weight:${weight};font-display:swap}`);
  face("BDRounded", 500, f["ResourceHanRoundedCN-Medium"]);
  face("BDRounded", 700, f["ResourceHanRoundedCN-Bold"]);
  const style = document.createElement("style");
  style.textContent = css.join("\n");
  document.head.append(style);
}
