//! Interaction fuzzer: random play + invariants + metamorphic checks.
//!
//! Black-box. Nothing under `rules/cards/`, `rules/skills/`, `rules/fixtures/`
//! or `target/scratch/tainted/` is opened; the generator reads the shipped
//! manifest at runtime and `docs/rulebook/footprints.json` for surface bias.

pub mod drive;
pub mod gen;
pub mod meta;
pub mod rng;

use drive::{AnswerMode, Trace};
use rng::Rng;

/// The signature of a known finding: a short substring of the failure text.
/// Entries point at the `#[ignore = "DISCREPANCY: …"]` test in
/// `tests/rb_fuzz_found.rs` that holds the minimal repro.
pub struct KnownFinding {
    pub signature: &'static str,
    pub points_at: &'static str,
}

/// Skip-list of findings already filed. The fuzzer stays green at the default
/// `FUZZ_ITERS` by recognising these signatures instead of re-tripping them.
/// Only signatures of *confirmed* findings belong here -- an over-broad
/// signature would swallow a new violation.
pub const KNOWN_FINDINGS: &[KnownFinding] = &[
    KnownFinding {
        signature: "money: player delta",
        points_at: "rb_fuzz_found::money_ledger_gap",
    },
    KnownFinding {
        signature: "unknown card id",
        points_at: "rb_fuzz_found::unknown_card_id",
    },
    KnownFinding {
        signature: "card_trap",
        points_at: "rb_fuzz_found::card_trap_reachable",
    },
    KnownFinding {
        signature: "settle: the match did not come to rest",
        points_at: "rb_fuzz_found::settle_loop_stuck",
    },
    KnownFinding {
        signature: "world_mut while a routine is pending",
        points_at: "rb_fuzz_found::settle_loop_stuck",
    },
];

/// Is `err` a signature we have already filed?
pub fn is_known(err: &str) -> Option<&'static str> {
    KNOWN_FINDINGS
        .iter()
        .find(|k| err.contains(k.signature))
        .map(|k| k.points_at)
}

/// A failure, shrunk to a minimal reproduction.
#[derive(Clone, Debug)]
pub struct Finding {
    pub seed: u64,
    pub iters: u32,
    pub what: String,
    pub repro: String,
}

impl Finding {
    /// Render as a ready-to-paste `#[test]` built on `Table`.
    pub fn as_test(&self, name: &str) -> String {
        format!(
            "/// Auto-generated by the interaction fuzzer (seed {seed}).\n\
             /// {what}\n\
             #[test]\n\
             #[ignore = \"DISCREPANCY: {what}\"]\n\
             fn {name}() {{\n\
             \x20   // {repro}\n\
             \x20   let mut t = common::Table::with_seed(&[\"户山香澄\", \"花园多惠\"], {seed});\n\
             \x20   // Re-derive the failing run:\n\
             \x20   //   FUZZ_ITERS={iters} cargo test -p game-rules --test fuzz_interactions -- --nocapture\n\
             \x20   let mut rng = fuzz::rng::Rng::new({seed} ^ 0xA5A5);\n\
             \x20   let tr = fuzz::drive::drive(&mut t, &mut rng, {iters}, fuzz::drive::AnswerMode::Free).unwrap();\n\
             \x20   // {what}\n\
             \x20   let _ = tr;\n\
             \x20   panic!(\"{what}\");\n\
             }}\n",
            seed = self.seed,
            what = self.what.escape_debug(),
            repro = self.repro.escape_debug(),
            iters = self.iters,
        )
    }
}

/// Shrink a failing run: fewer turns, then fewer players, then a quieter
/// arrangement. `probe(seed, iters, n_players)` must return Err for the
/// original and Ok once the failure is gone.
pub fn shrink(
    seed: u64,
    iters: u32,
    n_players: usize,
    mut probe: impl FnMut(u64, u32, usize) -> Result<(), String>,
) -> (u64, u32, usize) {
    let mut best = (seed, iters, n_players);
    // Fewer turns.
    let mut it = iters;
    while it > 1 {
        let cand = (seed, it - 1, n_players);
        if probe(cand.0, cand.1, cand.2).is_err() {
            best = cand;
            it -= 1;
        } else {
            break;
        }
    }
    // Fewer players (floor of 2).
    let mut n = n_players;
    while n > 2 {
        let cand = (best.0, best.1, n - 1);
        if probe(cand.0, cand.1, cand.2).is_err() {
            best = cand;
            n -= 1;
        } else {
            break;
        }
    }
    // Try nearby seeds (a quieter board often reproduces with fewer moving
    // parts). Bounded so the shrink stays cheap.
    for d in 1..8u64 {
        let cand = (best.0.wrapping_add(d), best.1, best.2);
        if probe(cand.0, cand.1, cand.2).is_err() {
            best = cand;
            break;
        }
    }
    best
}

/// Run one iteration of the fuzzer. Returns the trace and any finding.
/// Panics inside the driver (`settle` never resting, `world_mut` asserts) are
/// caught and turned into findings so one bad seed cannot abort the soak.
pub fn one_iter(seed: u64, turns: u32) -> Result<Trace, Finding> {
    let run = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| -> Result<Trace, String> {
        let (mut t, _cards) = gen::arrange(seed);
        let mut rng = Rng::new(seed ^ 0xA5A5);
        let known = gen::all_card_ids();
        let mut tr = Trace::new();
        for _ in 0..turns {
            let before: Vec<i32> = (0..t.n).map(|i| t.money(i)).collect();
            let mark = t.mark();
            let sub = drive::drive(&mut t, &mut rng, 1, AnswerMode::Free)?;
            tr.acts += sub.acts;
            tr.prompts += sub.prompts;
            tr.counteracts += sub.counteracts;
            tr.traps += sub.traps;
            tr.pairs_this_turn.extend(sub.pairs_this_turn);
            for (k, v) in sub.unaccounted_money {
                *tr.unaccounted_money.entry(k).or_default() += v;
            }
            let after: Vec<i32> = (0..t.n).map(|i| t.money(i)).collect();
            let events = t.events_since(mark);
            drive::check_money(&before, &after, &events, &mut tr)?;
            drive::check_nonneg(&t)?;
            drive::check_cards(&t, known)?;
        }
        Ok(tr)
    }));
    let run = match run {
        Ok(r) => r,
        Err(panic) => {
            let what = panic
                .downcast_ref::<String>()
                .cloned()
                .or_else(|| panic.downcast_ref::<&str>().map(|s| s.to_string()))
                .unwrap_or_else(|| "driver panicked".to_string());
            Err(what)
        }
    };
    match run {
        Ok(tr) => Ok(tr),
        Err(what) => {
            if let Some(points_at) = is_known(&what) {
                eprintln!("known finding ({points_at}): {what}");
                // Count it so the coverage report can cite per-kind totals.
                let mut tr = Trace::new();
                *tr.unaccounted_money
                    .entry(points_at.to_string())
                    .or_default() += 1;
                return Ok(tr);
            }
            let probe = |s: u64, it: u32, n: usize| -> Result<(), String> {
                let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let chars = crate::common::characters();
                    let cs: Vec<String> = chars.iter().take(n).cloned().collect();
                    let refs: Vec<&str> = cs.iter().map(String::as_str).collect();
                    let mut t = crate::common::Table::with_seed(&refs, s);
                    let mut rng = Rng::new(s ^ 0xA5A5);
                    let known = gen::all_card_ids();
                    for _ in 0..it {
                        let before: Vec<i32> = (0..t.n).map(|i| t.money(i)).collect();
                        let mark = t.mark();
                        drive::drive(&mut t, &mut rng, 1, AnswerMode::Free)?;
                        let after: Vec<i32> = (0..t.n).map(|i| t.money(i)).collect();
                        let events = t.events_since(mark);
                        let mut tr = Trace::new();
                        drive::check_money(&before, &after, &events, &mut tr)?;
                        drive::check_nonneg(&t)?;
                        drive::check_cards(&t, known)?;
                    }
                    Ok::<(), String>(())
                }));
                match r {
                    Ok(Ok(())) => Ok(()),
                    Ok(Err(e)) => Err(e),
                    Err(_) => Err("probe panicked (likely the same failure)".into()),
                }
            };
            let (s, it, n) = shrink(seed, turns, 4, probe);
            Err(Finding {
                seed: s,
                iters: it,
                what,
                repro: format!("seed={s} iters={it} players={n}"),
            })
        }
    }
}