//! The shipped card ruleset: every band's table in one module.
//!
//! Generated by `tools/rules-aggregate.mjs` -- do not edit. The band crates
//! stay one-per-band (and one .rs per card) for authors; unifying the
//! *artifact* keeps the SDK and allocator linked once instead of once per
//! band, which is most of the size of a module.

#![cfg_attr(target_arch = "wasm32", no_std)]

card_sdk::bandori_ruleset!(
    card_ag::CARDS,
    card_crychic::CARDS,
    card_general::CARDS,
    card_hhw::CARDS,
    card_morfonica::CARDS,
    card_mujica::CARDS,
    card_mygo::CARDS,
    card_pp::CARDS,
    card_ppp::CARDS,
    card_ras::CARDS,
    card_roselia::CARDS,
    card_sumimi::CARDS
);
